spring.application.name=temperaturyapi
spring.datasource.url=jdbc:mysql://sql7.freesqldatabase.com:3306/sql7762232?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=sql7762232
spring.datasource.password=FPfuQeVDs8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=3000
